### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-semantic-elements-5BSgA-#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by stuartpearman** [comment]
Hey Amanuel,

The way you're using your`section` tags is actually how we want you to use `article` tags, and where you have your `article` tags now doesn't need to necessarily be replaced by anything, but you could use a `section` there if you want to.

Make sure to include this project criteria:

> Each product includes a nav element with one or more links to related products (the links don't have to go anywhere)

Also, you're using the `header` tag correctly in the `main` content area, but you need to include a header in each product as well:

> For each product, correctly use an article, header, and footer element

You could use the header to display the name of the product.

Let me know when you're ready for me to look at these again 👍

**Comment by amanuel1995** [comment]
I did as you suggested!

**Comment by stuartpearman** [comment]
Hi Amanuel,

The only other thing I would change here is that you have nested `article` tags. You have a `.products` article and a `.text` article. The `products` articles are being used correctly, but the `text` articles should probably be sections or divs. The difference is that `article` tags should signify a standalone grouping of content.

For added context, If you made a separate page for only what's in the `.products` article, it would make sense as a standalone product page. If you did the same for the `.text` article, it would just be the one paragraph describing the product. Without the rest of the information (the name, image), it would be a little out of context.

Does that make sense? Let me know if you have any questions and comment back when you're done :+1:

**Comment by amanuel1995** [comment]
Yes, it does make sense. I was also suspicious. I just try to avoid generic containers like div and sections that don't tell the browser any specific semantic information.

I made the change.

**Comment by stuartpearman** [comment]
Looks good Amanuel! I guess I forgot to make sure you had made this change last time:

> Each product includes a nav element with one or more links to related products (the links don't have to go anywhere)

You have a top level navigation, but you'll actually include a `nav` element for _each product_ linking to "related" products (they don't have to link to anything).

**Comment by stuartpearman** [comment]
Much better! :shipit:

**Comment by amanuel1995** [comment]
:+1:
